version: '3.9'

services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: chauhankrutarth2
      MONGO_INITDB_ROOT_PASSWORD: Krutarth123

  server:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - uploads:/app/public/uploads
      - /app/node_modules
    env_file:
      - ./config/.env
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chauhankrutarth2
      ME_CONFIG_MONGODB_ADMINPASSWORD: Krutarth123
      ME_CONFIG_MONGODB_URL: mongodb+srv://chauhankrutarth2:Krutarth123@cluster0.fzarsjy.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0

volumes:
  uploads:
  data:
